version: '3.8'

services:
  backend:
    build: ./flask-server
    container_name: assignment-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MONGODB_URI=mongodb+srv://<username>:<password>@cluster0.xxxxx.mongodb.net/assignment_checker
      - FRONTEND_URLS=http://localhost
      - BACKEND_URL=http://backend:5000
    # No depends_on mongo, using Atlas

  frontend:
    build: ./client
    container_name: assignment-frontend
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

# Removed local mongo service and volume, using Atlas 